In [ ]:
def missingWord(s,t):
    s = s.split()
    print s
    t = t.split()
    print t
    for word in t:
        if word in s:
            s.remove(word)
        else:
            pass
    return s
   
                
    

In [ ]:
# print missingWord("I am using HackerRank to improve programming","am HackerRank to improve")
print missingWord("I    On  like cheese","I , cheese")

In [ ]:
def electionWinner(votes):
    voteDict = {}
    maxcand = []
    for vote in votes:
        voteDict[vote] = voteDict.get(vote,0) + 1
    name = dict.keys(voteDict)
    nameval = dict.values(voteDict)
    maxvote = max(nameval)
    
    for vote in voteDict:
        if voteDict[vote] == maxvote:
            if len(maxcand) == 0:
                maxcand.append(vote)
            else:
                if vote > maxcand[0]:
                    maxcand.insert(0, vote)
                else:
                    maxcand.append(vote)
                    
    return maxcand[0]
            


In [1]:
def BinaryTree(r):
    return [r, [], []]

def insertLeft(root,newBranch):
    t = root.pop(1)
    if len(t) > 1:
        root.insert(1,[newBranch,t,[]])
    else:
        root.insert(1,[newBranch, [], []])
    return root

def insertRight(root,newBranch):
    t = root.pop(2)
    if len(t) > 1:
        root.insert(2,[newBranch,[],t])
    else:
        root.insert(2,[newBranch,[],[]])
    return root

def getRootVal(root):
    return root[0]

def setRootVal(root,newVal):
    root[0] = newVal

def getLeftChild(root):
    return root[1]

def getRightChild(root):
    return root[2]

In [22]:
def textQueries(sentences,queries):
    sentDict = {}
    sentList = []
    for i,sent in enumerate(sentences):
        sentDict[sent] = i
    print sentDict
    
#     for keys in 
    
    
    
    newWordList = []
    
    for words in queries:
        word = words.split()
        miniList =[]
        for i in word:
            miniList.append(i)
        newWordList.append(miniList)
    print newWordList
    
    for i in newWordList:
        for j in i:
            if j in 

In [23]:
sentences = ["how it was done","are you how","it goes to","goes done are it"]
queries = ["done it","it"]

print textQueries(sentences,queries)


{'it goes to': 2, 'how it was done': 0, 'are you how': 1, 'goes done are it': 3}
[['done', 'it'], ['it']]
None


In [27]:
class Vertex:
    def __init__(self, vertex):
        self.name = vertex
        self.neighbors = []
        
    def add_neighbor(self, neighbor):
        if isinstance(neighbor, Vertex):
            if neighbor.name not in self.neighbors:
                self.neighbors.append(neighbor.name)
                neighbor.neighbors.append(self.name)
                self.neighbors = sorted(self.neighbors)
                neighbor.neighbors = sorted(neighbor.neighbors)
        else:
            return False
        
    def add_neighbors(self, neighbors):
        for neighbor in neighbors:
            if isinstance(neighbor, Vertex):
                if neighbor.name not in self.neighbors:
                    self.neighbors.append(neighbor.name)
                    neighbor.neighbors.append(self.name)
                    self.neighbors = sorted(self.neighbors)
                    neighbor.neighbors = sorted(neighbor.neighbors)
            else:
                return False
        
    def __repr__(self):
        return str(self.neighbors)

class Graph:
    def __init__(self):
        self.vertices = {}
    
    def add_vertex(self, vertex):
        if isinstance(vertex, Vertex):
            self.vertices[vertex.name] = vertex.neighbors

            
    def add_vertices(self, vertices):
        for vertex in vertices:
            if isinstance(vertex, Vertex):
                self.vertices[vertex.name] = vertex.neighbors
            
    def add_edge(self, vertex_from, vertex_to):
        if isinstance(vertex_from, Vertex) and isinstance(vertex_to, Vertex):
            vertex_from.add_neighbor(vertex_to)
            if isinstance(vertex_from, Vertex) and isinstance(vertex_to, Vertex):
                self.vertices[vertex_from.name] = vertex_from.neighbors
                self.vertices[vertex_to.name] = vertex_to.neighbors
                
    def add_edges(self, edges):
        for edge in edges:
            self.add_edge(edge[0],edge[1])          
    
    def adjacencyList(self):
        if len(self.vertices) >= 1:
                return [str(key) + ":" + str(self.vertices[key]) for key in self.vertices.keys()]  
        else:
            return dict()
        
    def adjacencyMatrix(self):
        if len(self.vertices) >= 1:
            self.vertex_names = sorted(g.vertices.keys())
            self.vertex_indices = dict(zip(self.vertex_names, range(len(self.vertex_names)))) 
            import numpy as np
            self.adjacency_matrix = np.zeros(shape=(len(self.vertices),len(self.vertices)))
            for i in range(len(self.vertex_names)):
                for j in range(i, len(self.vertices)):
                    for el in g.vertices[self.vertex_names[i]]:
                        j = g.vertex_indices[el]
                        self.adjacency_matrix[i,j] = 1
            return self.adjacency_matrix
        else:
            return dict()              
                        
def graph(g):
    """ Function to print a graph as adjacency list and adjacency matrix. """
    return str(g.adjacencyList()) + '\n' + '\n' + str(g.adjacencyMatrix())

###################################################################################

a = Vertex('A')
b = Vertex('B')
c = Vertex('C')
d = Vertex('D')
e = Vertex('E')

a.add_neighbors([b,c,e]) 
b.add_neighbors([a,c])
c.add_neighbors([b,d,a,e])
d.add_neighbor(c)
e.add_neighbors([a,c])
        
g = Graph()
print graph(g)
print 
g.add_vertices([a,b,c,d,e])
g.add_edge(b,d)
print graph(g)

{}

{}

["A:['B', 'C', 'E']", "C:['A', 'B', 'D', 'E']", "B:['A', 'C', 'D']", "E:['A', 'C']", "D:['B', 'C']"]

[[ 0.  1.  1.  0.  1.]
 [ 1.  0.  1.  1.  0.]
 [ 1.  1.  0.  1.  1.]
 [ 0.  1.  1.  0.  0.]
 [ 1.  0.  1.  0.  0.]]


In [26]:
g = Graph()
g.connect(6,9)
g.connect(8,9)
g.connect(3,5)
g.connect(6,7)
g.connect(4,8)
g.connect(1,8)
g.connect(8,10)
g.connect(5,8)
g.connect(1,2)
 
g.paint()


a = Vertex('A')
b = Vertex('B')
c = Vertex('C')
d = Vertex('D')
e = Vertex('E')

a.add_neighbors([b,c,e]) 
b.add_neighbors([a,c])
c.add_neighbors([b,d,a,e])
d.add_neighbor(c)
e.add_neighbors([a,c])
        
g = Graph()
print graph(g)
print 
g.add_vertices([a,b,c,d,e])
g.add_edge(b,d)
print graph(g)

{1: {8: 1, 2: 1}, 2: {}, 3: {5: 1}, 4: {8: 1}, 5: {8: 1}, 6: {9: 1, 7: 1}, 7: {}, 8: {9: 1, 10: 1}, 9: {}, 10: {}}
